name: Smoke Tests - PR
on:
  pull_request:
    branches: [ master ]

jobs:
  RunTest:
    runs-on: windows-latest
    steps:
      - name: Clonar o projeto
        uses: actions/checkout@v3

      - name: Instalar Java 11
        uses: actions/setup-java@v4
        with:
          java-version: '11'
          distribution: 'adopt'
          cache: 'maven'

      - name: Instalar Chrome
        uses: browser-actions/setup-chrome@v2

      - name: Instalar ChromeDriver
        uses: nanasess/setup-chromedriver@v2

      - name: Start ChromeDriver
        run: chromedriver --url-base=/wd/hub &

      - name: Rodar testes Maven
        run: mvn test -Dtest=RunCucumber -Dbrowser=chrome-ci
